// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadClipboard():Promise<string>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<string>;

export function WriteClipboard(arg1:string):Promise<void>;
