// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadClipboard() {
  return window['go']['main']['Desktop']['ReadClipboard']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['Desktop']['SaveFile'](arg1, arg2);
}

export function WriteClipboard(arg1) {
  return window['go']['main']['Desktop']['WriteClipboard'](arg1);
}
